### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by lexrus** [producthunt/producthunt-osx#1]
1. There's no Keys-Example.xcconfig in the root folder `cp: Keys-Example.xcconfig: No such file or directory`
2. The subproject LaunchAtLoginHelper can't be built because it has not Info.plist.

<img width="818" alt="screen shot 2016-04-22 at 9 52 39 am" src="https://cloud.githubusercontent.com/assets/219689/14729416/33216900-0870-11e6-81c9-6ed98b82b5bd.png">

**Comment by devladinci** [comment]
Sorry, my bad.
1. For configuration templates `cp Source/Config/Keys-Example.xcconfig Source/Config/Keys.xcconfig` update in `README`.
2. Accidentally `LLStrings` were included in `.gitignore`  Properties from `LLStrings.h` are now inlined in `LaunchAtLoginHelper`
