### ISSUE TITLE
How to fill in the configurations in `Keys.config` file?

### ISSUE THREAD

**Issue by hujiaweibujidao** [producthunt/producthunt-osx#6]
Hi all, I have got the `PRODUCT_HUNT_APP_ID` and `PRODUCT_HUNT_APP_SECRET` in `Keys.config` file, but how should I fill in the other three configurations? 

```
PRODUCT_HUNT_APP_ID = @"APP_ID_KEY"
PRODUCT_HUNT_APP_SECRET = @"APP_SECRET_KEY"

PRODUCT_HUNT_FEED_URL = @"PRODUCT_HUNT_FEED_URL"

SEGMENT_PRODUCTION_WRITE_KEY = @"SEGMENT_PRODUCTION_WRITE_KEY"
SEGMENT_DEVELOPMENT_WRITE_KEY = @"SEGMENT_DEVELOPMENT_WRITE_KEY"
```

Thanks.

**Comment by hujiaweibujidao** [comment]
`SEGMENT_xxx_KEY ` seems to be related to `Analytics`, right?

Then, what is the right value for `PRODUCT_HUNT_FEED_URL `?

Thanks.

**Comment by devladinci** [comment]
Yeah my bad, I'm going to remove `Segment` key and `feed url `from config file. App should compile and work as it is.

**Comment by hujiaweibujidao** [comment]
@devladinci Thanks. I'm currently reading the source code of this project, and many thanks to your efforts for sharing this project. :-)

**Comment by devladinci** [comment]
@hujiaweibujidao Always welcome :)
