### ISSUE TITLE
I can't get the latest news. The Latest time is "yesterday" 

### ISSUE THREAD

**Issue by lk1ngaa7** [producthunt/producthunt-osx#7]
![image](https://cloud.githubusercontent.com/assets/5397716/15492096/2e93f18e-21aa-11e6-8756-f07ec79a84c9.png)
Pos : China

**Comment by devladinci** [comment]
@lk1ngaa7 ProductHunt uses `Pacific Time Zone` (PST) for posts and days. In your case I think you're in `CST` time zone witch is 2 hours ahead. This is the reason why you don't see `today's` posts because in PST is still previous day. At first I was confused too because I'm 10 hours ahead :)

**Comment by lk1ngaa7** [comment]
@devladinci Thank you.
